## Site settings
##############################################
title: "siimple"
subtitle: "colors"
description: "An elegant and minimalistic color palette for UI design"
version: "1.0.0"
author: "Josemi Juanes and Pablo Marin-Garcia"
url: "https://colors.siimple.xyz"
license: "MIT License"
repository: "https://github.com/siimple/siimple-colors"
releases: "https://github.com/siimple/siimple-colors/releases"
links:
    - title: "Usage"
      url: "/usage.html"
    - title: "Colors"
      url: "/colors.html"
    - title: "GitHub"
      url: "https://github.com/siimple/siimple-colors"
      target: "_blank"

## Theme configuration
##############################################
theme_config:
    color: "watermelon"
    custom_styles: ["/assets/css/main.css"]
    changes_url: "https://github.com/ssimple/siimple-colors/issues/new"
    analytics: "UA-70800807-6"
    legal_urls:
        cookies: "https://www.siimple.xyz/legal/cookies.html"
        privacy: "https://www.siimple.xyz/legal/privacy.html"
    copyright: "&copy; 2015-present <strong>siimple</strong>"

## Build settings
##############################################
env: "production"
permalink: "/:title.html"
theme: "siimple-theme"
# Exclude files
exclude: ["LICENSE", "Gemfile", "Gemfile.lock"]

