runtime: python27
api_version: 1
threadsafe: yes
service: colors

handlers:

- url: /css
  static_dir: css
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /
  mime_type: text/html
  static_files: index.html
  upload: index.html
  secure: always

- url: /(.+).html
  mime_type: text/html
  static_files: \1.html
  upload: (.+)
  secure: always
